server {
    listen 80;
    server_name parabellum-erp.online www.parabellum-erp.online;

    client_max_body_size 20m;
    client_header_buffer_size 32k;
    large_client_header_buffers 8 128k;
    gzip off;
    resolver 127.0.0.11 ipv6=off valid=10s;

    location /api/ {
        set $api_upstream api-gateway:3001;
        proxy_pass http://$api_upstream$request_uri;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /_next/static/ {
        set $frontend_upstream frontend:3000;
        proxy_pass http://$frontend_upstream$request_uri;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Accept-Encoding "";
    }

    location / {
        set $frontend_upstream frontend:3000;
        proxy_pass http://$frontend_upstream$request_uri;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Accept-Encoding "";
    }
}
