packages: []

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  '@scarf/scarf': true
  unrs-resolver: true
  canvas: true
  puppeteer: true
  puppeteer-core: true

networkConcurrency: 8
fetchRetries: 5
fetchRetryFactor: 2
fetchRetryMintimeout: 20000
fetchRetryMaxtimeout: 120000
fetchTimeout: 300000