export const LOGIPAIE_SHEETS = {
  "1-ACCUEIL": [
    "© Copyright 2023, LOGIPAIE_RH V24.01, tous droits réservés"
  ],
  "2-MODE D'EMPLOI": [
    "LOGIPAIE_RH V24.01",
    "Page 1/2",
    "LOGIPAIE_RH V24.01",
    "Page 2/2"
  ],
  "3-PARAMÈTRES": [
    "ADRESSE:",
    "BP",
    "5115 ABIDJAN 01",
    "TELEPHONE:",
    "e-mail:",
    "erickouassi17@gmail.com",
    "NOVEMBRE",
    "30/11/2024",
    "NOVEMBRE",
    "30/11/2023",
    "NOVEMBRE"
  ],
  "4-CUMULS": [
    "CUMUL GENERAL",
    "Noms & Prénoms",
    "Sexe ",
    "Date de\r\nNaissance",
    "Nationalité",
    "Code Nationalité",
    "Situation matrimoniale",
    "Nombre d'enfants",
    "Part(s)\r\nIGR",
    "Adresse",
    "Téléphone",
    "Date d'Entrée",
    "Date de Sortie",
    "Direction",
    "Service",
    "Emploi",
    "Code Emploi",
    "Régime",
    "Type",
    "Catégorie",
    "N° CNPS",
    "SALAIRE",
    "Primes et Indemnités imposables",
    "Gratification",
    "Congé",
    "Préavis et indemnité de licenciement",
    "BRUT FISCAL Salarié",
    "Primes et Indem. non imposables Salarié",
    "BRUT FISCAL employeur",
    "Autres indem. non imposables",
    "Brut social",
    "Transport non imposable",
    "Indemnités non taxables",
    "TOTAL GAINS",
    "IS",
    "Retraite",
    "Avance Acompte",
    "Assurance",
    "CMU",
    "Prêt",
    "Autres retenues",
    "Arrondis",
    "NET A PAYER",
    "Jours Travaillés",
    "HT",
    "Congés payés, CP",
    "Nbre CP",
    "Mois Travaillés",
    "JT+CP",
    "Plafond si mois de sortie",
    "TOTAL MOIS TRAVAILLES"
  ],
  "5-LE PERSONNEL": [
    "Matricule",
    "Civilité",
    "Noms & Prénoms",
    "Sexe",
    "Date de Naissance",
    "Lieu de Naissance",
    "Nature Pièce d'Identité",
    "Numéro Pièce d'Identité",
    "Nationalité",
    "Code Nationalité",
    "Situation matrimoniale",
    "Nombre d'enfants",
    "Part(s) IGR",
    "Adresse",
    "Téléphone",
    "Lieu d'Habitation",
    "Contrat",
    "Date de Signature du Contrat",
    "Durée Contrat CDD (mois)",
    "Date d'Entrée",
    "Date de Sortie",
    "Direction",
    "Service",
    "Emploi",
    "Code Emploi",
    "Régime",
    "Type",
    "Catégorie",
    "Non soumis CNPS, cochez (X)",
    "N° CNPS",
    "Mode de Paiement",
    "Numéro de Compte Bancaire",
    "Banque",
    "Civilité (liste)",
    "Matricule (liste)",
    "Civilité",
    "Sexe",
    "Code Nationalité",
    "Situation matrimoniale",
    "Code Emploi",
    "Régime",
    "Type",
    "Catégorie",
    "Mode de Paiement",
    "Contrat",
    "Non soumis CNPS, cochez (X)",
    "Liste CDD",
    "Liste CDI"
  ],
  "6-CONTRAT DE TRAVAIL CDI": [
    "Civilité",
    "Nom et prénoms",
    "Date de naissance",
    "Lieu de naissance",
    "Nationalité",
    "Adresse",
    "Poste",
    "Catégorie",
    "Direction",
    "Service",
    "Date d'entrée",
    "Salaire brut mensuel",
    "Prime de transport",
    "Période d'essai (mois)",
    "Lieu de travail",
    "Nature pièce d'identité",
    "Numéro pièce d'identité",
    "Régime",
    "Type",
    "Mode de paiement",
    "Banque",
    "RIB"
  ],
  "7-CONTRAT DE TRAVAIL CDD": [
    "Civilité",
    "Nom et prénoms",
    "Date de naissance",
    "Lieu de naissance",
    "Nationalité",
    "Adresse",
    "Poste",
    "Catégorie",
    "Direction",
    "Service",
    "Date d'entrée",
    "Date de fin prévue",
    "Salaire brut mensuel",
    "Prime de transport",
    "Durée CDD (mois)",
    "Motif",
    "Lieu de travail",
    "Nature pièce d'identité",
    "Numéro pièce d'identité",
    "Régime",
    "Type",
    "Mode de paiement",
    "Banque",
    "RIB"
  ],
  "8-ATTESTATION DE TRAVAIL": [
    "Civilité",
    "Nom et prénoms",
    "Sexe",
    "Nationalité",
    "Code nationalité",
    "Situation matrimoniale",
    "Adresse",
    "Téléphone",
    "Direction",
    "Service",
    "Emploi",
    "Code emploi",
    "Régime",
    "Type",
    "Catégorie",
    "Mode de paiement",
    "Date d'entrée"
  ],
  "9-TRAITEMENT DE LA PAIE": [
    "Jour(s) travaillés",
    "SALAIRE DE BASE",
    "HEURES SUP.",
    "PRIME D'ANCIENNETE",
    "PRIME DE TRANSPORT",
    "AUTRES PRIMES ET INDEMNITES",
    "Congé payé",
    "Gratification",
    "Préavis",
    "Indemnité de licenciement",
    "Indemnité transactionnelle de rupture",
    "Frais funéraires",
    "RETENUES FISCALES ET SOCIALES",
    "AUTRES RETENUES",
    "TOTAL RETENUES",
    "31/01/2024",
    "PART(S) IGR",
    "BRUT",
    "tranche 1",
    "tranche 2",
    "tranche 3",
    "tranche 4",
    "tranche 5",
    "tranche 6",
    "ITS avant RICF",
    "RICF",
    "ITS"
  ],
  "10-HEURES SUPPLEMENTAIRES": [
    "MATRICULE",
    "NOM ET PRÉNOMS",
    "Salaire Catégoriel Mensuel",
    "Salaire horaire",
    "De la 41è à la 46è heure",
    "Au-delà de la 46è heure",
    "Heures effectuées de nuit",
    "Heures effectuées de jour, les dimanches et jours fériés",
    "Heures effectuées de nuit, les dimanches et jours fériés",
    "Montant 41è à 46è heure",
    "Montant au-delà de la 46è heure",
    "Montant heures de nuit",
    "Montant heures jour (dimanches/jours fériés)",
    "Montant heures de nuit (dimanches/jours fériés)"
  ],
  "11-CONGÉS": [
    "MATRICULE",
    "LISTE DU PERSONNEL",
    "DATE D'ENTREE",
    "DATE DE RETOUR DU DERNIER CONGÉ",
    "SALAIRE MOYEN",
    "DATE DE DEPART EN CONGÉ",
    "ANCIENNETÉ (année)",
    "PÉRIODE DE RÉFÉRENCE",
    "DURÉE CONGÉ",
    "MAJORATION",
    "DURÉE TOTALE CONGÉ",
    "CONGÉ PAYÉ",
    "DATE DE FIN DE CONGE"
  ],
  "12-ATTESTATION DE CONGÉS": [
    "Civilité",
    "Nom et prénoms",
    "Sexe",
    "Nationalité",
    "Code nationalité",
    "Situation matrimoniale",
    "Adresse",
    "Téléphone",
    "Direction",
    "Service",
    "Emploi",
    "Code emploi",
    "Régime",
    "Type",
    "Catégorie",
    "Mode de paiement",
    "Date départ congé",
    "Date retour congé",
    "Durée congé"
  ],
  "13-GRATIFICATIONS": [
    "MATRICULE",
    "LISTE DU PERSONNEL",
    "DATE D'ENTREE",
    "BASE",
    "PRORATA",
    "TAUX PONDÉRÉ",
    "GRATIFICATION"
  ],
  "14-INDEMNITES DE RUPTURE": [
    "MATRICULE",
    "NOM ET PRÉNOMS",
    "DATE D'ENTÉE",
    "CONTRAT",
    "SALAIRE CATÉGORIEL",
    "TYPE",
    "STATUT",
    "MOTIF DE LA RUPTURE",
    "DATE DE SORTIE",
    "DATE RETOUR DERNIER CONGE",
    "SALAIRE MOYEN MENSUEL",
    "SALAIRE PÉRIODE CDD",
    "GRATIFICATION",
    "INDEMNITÉ CONVENTIONNELLE DE RUPTURE",
    "NOMBRE DE MOIS PRÉAVIS EFFECTUÉS",
    "PRÉAVIS",
    "INDEMNITÉ DE LICENCIEMENT",
    "CONGÉS",
    "GRATIFICATION",
    "PARTICIPATION AUX FRAIS FUNÉRAIRES ",
    "INDEMNITÉ DE RUPTURE CONVENTIONNELLE",
    "TOTAL",
    "MOTIF DU LICENCIEMENT",
    "ANCIENNETE (année)",
    "INDEMNITE DE LICENCIEMENT",
    "PERIODE DE REFERENCE CONGE (mois)",
    "DUREE CONGE (jours)",
    "MAJORATION (jours)",
    "DUREE TOTAL CONGE (JOURS):",
    "CONGE PAYE",
    "DATE DE DEBUT D'ANNEE",
    "PERIODE DE REFERENCE GRATIFICATION (jours)",
    "GRATIFICATION",
    "TYPE",
    "STATUT",
    "Horaire ou journalier",
    "Employé ou ouvrier",
    "Cadre, Agent de maîtrise",
    "Durée Préavis",
    "Aggravation Préavis",
    "Nombre de Mois Preavis Effectues",
    "PREAVIS (mois)",
    "PARTICIPATION AUX FRAIS FUNERAIRES (mois)",
    "PREAVIS",
    "INDEMNITE DE LICENCIEMENT",
    "CONGES",
    "GRATIFICATION",
    "PARTICIPATION AUX FRAIS FUNERAIRES ",
    "PREAVIS",
    "INDEMNITE DE LICENCIEMENT",
    "CONGES",
    "GRATIFICATION",
    "PARTICIPATION AUX FRAIS FUNERAIRES "
  ],
  "15-CERTIFICAT DE TRAVAIL": [
    "Civilité",
    "Nom et prénoms",
    "Sexe",
    "Nationalité",
    "Code nationalité",
    "Situation matrimoniale",
    "Adresse",
    "Téléphone",
    "Direction",
    "Service",
    "Emploi",
    "Code emploi",
    "Régime",
    "Type",
    "Catégorie",
    "Mode de paiement",
    "Date d'entrée",
    "Date de sortie"
  ],
  "16-DONNÉES RNS": [
    "NBRE MOIS",
    "MONTANT",
    "OBSERVATIONS",
    "NBRE MOIS",
    "MONTANT",
    "OBSERVATIONS",
    "NBRE MOIS",
    "MONTANT",
    "OBSERVATIONS",
    "NBRE MOIS",
    "MONTANT",
    "OBSERVATIONS",
    "NBRE MOIS",
    "MONTANT",
    "OBSERVATIONS",
    "NBRE MOIS",
    "MONTANT",
    "OBSERVATIONS",
    "NBRE MOIS",
    "MONTANT",
    "OBSERVATIONS",
    "NBRE MOIS",
    "MONTANT",
    "OBSERVATIONS",
    "NBRE MOIS",
    "MONTANT",
    "OBSERVATIONS",
    "NBRE MOIS",
    "MONTANT",
    "OBSERVATIONS",
    "NBRE MOIS",
    "MONTANT",
    "OBSERVATIONS",
    "NBRE MOIS",
    "MONTANT",
    "OBSERVATIONS",
    "NBRE MOIS",
    "MONTANT",
    "OBSERVATIONS",
    "NBRE MOIS",
    "MONTANT",
    "OBSERVATIONS",
    "NBRE MOIS",
    "MONTANT",
    "OBSERVATIONS",
    "NBRE MOIS",
    "MONTANT",
    "OBSERVATIONS",
    "NBRE MOIS",
    "MONTANT",
    "OBSERVATIONS",
    "NBRE MOIS",
    "MONTANT",
    "OBSERVATIONS",
    "NBRE MOIS",
    "MONTANT",
    "OBSERVATIONS",
    "NBRE MOIS",
    "MONTANT",
    "OBSERVATIONS",
    "NBRE MOIS",
    "MONTANT",
    "OBSERVATIONS",
    "NBRE MOIS",
    "MONTANT",
    "OBSERVATIONS",
    "NBRE MOIS",
    "MONTANT",
    "OBSERVATIONS",
    "NBRE MOIS",
    "MONTANT",
    "OBSERVATIONS",
    "NBRE MOIS",
    "MONTANT",
    "OBSERVATIONS",
    "NBRE MOIS",
    "MONTANT",
    "OBSERVATIONS",
    "NBRE MOIS",
    "MONTANT",
    "OBSERVATIONS",
    "NBRE MOIS",
    "MONTANT",
    "OBSERVATIONS",
    "NBRE MOIS",
    "MONTANT",
    "OBSERVATIONS",
    "NBRE MOIS",
    "MONTANT",
    "OBSERVATIONS"
  ],
  "17-RNS": [
    "NOM ET ADRESSE DE L'EMPLOYEUR",
    "N° EMPLOYEUR",
    "SALAIRES",
    "NOMBRE DE MOIS DE TRAVAIL DANS L'ANNEE",
    "DATE ET LIEU"
  ],
  "18-PRÊTS": [
    "DURÉE  (en mois)",
    "MENSUALITÉ",
    "DATE DE DEBUT",
    "DATE DE FIN",
    "PRELEVEMENT DU MOIS",
    "DÉJÀ PRELEVÉ",
    "EN MOIS",
    "RESTE À PRELEVER",
    "EN MOIS"
  ],
  "19-ÉDITION BULLETINS": [
    "Code",
    "Libellé",
    "Base",
    "Taux/Qté",
    "Gains",
    "Retenues",
    "Part patronale (base)",
    "Part patronale (taux/qté)",
    "Retenues patronales"
  ],
  "20-ÉDITION BULLETINS GROUPÉS": [
    "Code",
    "Libellé",
    "Base",
    "Taux/Qté",
    "Gains",
    "Retenues",
    "Part patronale (base)",
    "Part patronale (taux/qté)",
    "Retenues patronales"
  ],
  "21-LIVRE DE PAIE MENSUEL": [
    "MAT.",
    "NOM ET PRENOMS",
    "JOURS",
    "SALAIRE",
    "Primes et Indemnités imposables",
    "Gratification",
    "Congé",
    "Préavis et indemnité de licenciement",
    "BRUT FISCAL Salarié",
    "Primes et Indem. non imposables Salarié",
    "BRUT FISCAL Employeur",
    "Autres indem. non imposables",
    "BRUT SOCIAL",
    "Transport non imposable",
    "Indemnités non taxables",
    "TOTAL GAINS",
    "RETENUES",
    "Arrondis",
    "NET A PAYER",
    "LOCAL",
    "EXPATRIE",
    "AGRICOLE",
    "FERMAGE",
    "TOTAL",
    "JOURNALIERS <= 3 462",
    "JOURNALIERS > 3 462",
    "MENSUELS <= 75 000",
    "MENSUELS > 75 000 et <= 3 375 000",
    "MENSUELS > 3 375 000",
    "TOTAL (tranches)",
    "IGR AGRICOLE",
    "BRUT EMPLOYEUR"
  ],
  "22-ORDRE DE VIREMENT": [
    "Date",
    "N/Réf.",
    "Objet",
    "Banque destinataire",
    "Compte débité",
    "Montant",
    "Montant en lettres",
    "Motif",
    "Pièces jointes",
    "Signataire"
  ],
  "23-LISTE DES SALAIRES À VIRER": [
    "Banque",
    "Nom & prénoms",
    "RIB / Compte",
    "Montant net",
    "Code banque",
    "Code guichet",
    "Total banque"
  ],
  "24-DÉCLARATION ITS ": [
    "N°",
    "Nature des\r\nimpôts\r\n",
    "Catégorie de salariés",
    "Effectifs",
    "Revenu net imposable",
    "Taux",
    "Montant"
  ],
  "25-DÉCLARATION FDFP": [
    "NCC:",
    "1234567 A",
    "Objet ou activité:",
    "Logiciel de paie"
  ],
  "26-LISTE NOMINATIVE COTI. CNPS ": [
    "NUMERO CNPS",
    "NOM",
    "PRENOMS",
    "ANNEE DE NAISSANCE",
    "DATE D'EMBAUCHE",
    "DATE DE DEPART",
    "TYPE SALARIE \r\nM: Mensuel \r\nJ : Journalier \r\nH: Horaire",
    "DUREE TRAVAILLEE",
    "SALAIRE BRUT",
    "BRANCHE COTISEE\r\n1: Retraite \r\n2 : Accidents du Travail et Maladies Professionnelles \r\n3: Prestations Familiales et Assurance Maternite",
    "NUMERO CNPS",
    "NOM",
    "PRENOMS",
    "ANNEE DE NAISSANCE",
    "DATE D'EMBAUCHE",
    "DATE DE DEPART",
    "TYPE SALARIE \r\nM: Mensuel \r\nJ : Journalier \r\nH: Horaire",
    "DUREE TRAVAILLEE",
    "SALAIRE BRUT",
    "BRANCHE COTISEE\r\n1: Retraite \r\n2 : Accidents du Travail et Maladies Professionnelles \r\n3: Prestations Familiales et Assurance Maternite"
  ],
  "27-DÉCLARATION CNPS": [
    "Code opér.",
    "Date de journée",
    "N° Pièce",
    "Période",
    "Code Virement",
    "Banque",
    "Référence du titre de paiement",
    "Emission du",
    "Montant",
    "Visa DIRECTEUR"
  ],
  "28-IMPUTATIONS COMPTABLES": [
    "Jour",
    "N° pièce",
    "N° facture",
    "Référence",
    "N° compte général",
    "N° compte tiers",
    "Libéllé écriture",
    "Date échéance",
    "Débit ",
    "Crédit",
    "Jour",
    "N° pièce",
    "N° facture",
    "Référence",
    "N° compte général",
    "N° compte tiers",
    "Libéllé écriture",
    "Date échéance",
    "Position",
    "Débit ",
    "Crédit"
  ],
  "29-LIVRE DE PAIE ANNUEL": [
    "MAT.",
    "NOM ET PRENOMS",
    "JOURS",
    "SALAIRE",
    "Primes et Indemnités imposables",
    "Gratification",
    "Congé",
    "Préavis et indemnité de licenciement",
    "BRUT FISCAL Salarié",
    "Primes et Indem. non imposables Salarié",
    "BRUT FISCAL Employeur",
    "Autres indem. non imposables",
    "BRUT SOCIAL",
    "Transport non imposable",
    "Indemnités non taxables",
    "TOTAL GAINS",
    "RETENUES",
    "Arrondis",
    "NET A PAYER",
    "LOCAL",
    "EXPATRIE",
    "AGRICOLE",
    "FERMAGE",
    "TOTAL",
    "JOURNALIERS <= 3 462 F",
    "JOURNALIERS > 3 462 F",
    "MENSUELS <= 75 000",
    "MENSUELS > 75 000 et <= 3 375 000",
    "MENSUELS > 3 375 000",
    "TOTAL (tranches)",
    "IGR AGRICOLE",
    "BRUT EMPLOYEUR",
    "BRUT exonéré EMPLOYE",
    "BRUT exonéré EMPLOYEUR"
  ],
  "30-RECAP. MASSE SALARIALE": [
    "LIBELLES",
    "Janvier",
    "Février",
    "Mars",
    "Avril",
    "Mai",
    "Juin",
    "Juillet",
    "Août",
    "Septembre",
    "Octobre",
    "Novembre",
    "Décembre",
    "TOTAL"
  ],
  "31-ETAT 301 PAGE 1 (REGUL ITS)": [
    "N°",
    "Nature des impôts",
    "Personnel\r\nlocal Régime général\r\n",
    "Personnel\r\nexpatrié Régime général\r\n",
    "Régime        agricole",
    "TOTAL"
  ],
  "32-ETAT 301 PAGE 2 (DETAIL)": [
    "#",
    "N° CNPS",
    "Nom et prénoms",
    "Emploi ou Qualité",
    "Régime Général G\r\nou Agricole A",
    "Sexe",
    "Nationalité",
    "Local/Expatrié",
    "Etat civil",
    "Nombre d'enfants à charge",
    "Nombre de parts\r\nIGR",
    "Nombre de jours d'application des paiements",
    "Montant des salaires et rémunérations accessoires (ou pensions et rentes viagères)",
    "Montant des avantages en nature suivant barème réglementaire",
    "Montant des avantages en nature selon valeur réelle",
    "Salaire brut\r\n(14 + 15 ou\r\n16)",
    "ITS",
    "CN",
    "IGR",
    "Montant",
    "Désignation",
    "PARTS IGR",
    "Nbre de jours ouvrés",
    "Montant total annuel",
    "BRUT ANNUEL",
    "IS ANNUEL",
    "CN ANNUEL",
    "IGR ANNUEL",
    "IS",
    "CN",
    "IGR",
    "TRANSPORT",
    "AUTRES",
    "Crédit d'Impôt",
    "Crédit d'Impôt"
  ],
  "33-REGUL ANNUELLE FDFP": [
    "NCC:",
    "1234567 A",
    "Objet ou activité:",
    "Logiciel de paie"
  ],
  "34-DISA": [
    "NUM \r\nORDRE",
    "NOM",
    "PRENOM",
    "NUM CNPS",
    "ANNEE \r\nNAISS.",
    "DATE \r\nEMBAUCHE",
    "DATE \r\nDEPART",
    "TYPE \r\nSALARIE",
    "SALAIRE \r\nBRUT.",
    "DUREE \r\nACTIVITE",
    "MONTANT \r\nPF/AT.",
    "MONTANT \r\nRETRAITE",
    "REGIME",
    "OBSERVATION",
    "NOM",
    "PRENOM",
    "NUM CNPS",
    "ANNEE \r\nNAISS.",
    "DATE \r\nEMBAUCHE",
    "DATE \r\nDEPART",
    "TYPE \r\nSALARIE",
    "SALAIRE \r\nBRUT.",
    "DUREE \r\nACTIVITE jours",
    "DUREE \r\nACTIVITE mois",
    "MONTANT \r\nPF/AT.",
    "MONTANT \r\nRETRAITE",
    "REGIME",
    "OBSERVATION"
  ],
  "35-DASC": [
    "DATE DE JOURNEE",
    "N° DE PIECE",
    "PERIODE",
    "CODE VERSEMENT",
    "BANQUE",
    "REFERENCE DU TITRE DE PAIEMENT",
    "EMISSION DU",
    "MONTANT",
    "VISA"
  ],
  "36-FICHE INDIVIDUELLE": [
    "LIBELLES",
    "Janvier",
    "Février",
    "Mars",
    "Avril",
    "Mai",
    "Juin",
    "Juillet",
    "Août",
    "Septembre",
    "Octobre",
    "Novembre",
    "Décembre",
    "TOTAL",
    "SOUMAHORO KOROTOUMOU"
  ],
  "37-PROVISION CONGES": [
    "N°",
    "Nom et prénoms",
    "Régime",
    "Date d'entrée",
    "Date retour dernier congé",
    "Salaire brut moyen mensuel",
    "Période de référence (mois)",
    "Durée congé (jours)",
    "Majoration (jours)",
    "Durée totale congé (jours)",
    "Congé payé",
    "IS patronal",
    "Taxe FDFP",
    "CNPS retraite",
    "CNPS AT",
    "CNPS PF",
    "Provision congés",
    "N° (recap)",
    "Salariés",
    "Régime",
    "Date d'entrée",
    "Date retour dernier congé",
    "Salaire brut moyen mensuel",
    "Période de référence",
    "Durée congé (jours)",
    "Majoration",
    "Durée totale congé (jours)",
    "Congé payé",
    "IS patronal",
    "Taxe FDFP",
    "CNPS retraite",
    "CNPS AT",
    "CNPS PF",
    "Provision congés",
    "Cotisations patronales",
    "Taux"
  ],
  "38-PROVISION RETRAITE": [
    "N°",
    "Nom et prénoms",
    "Régime",
    "Date d'entrée",
    "Ancienneté (année)",
    "Salaire brut moyen mensuel",
    "Fraction 1 à 5 ans d'ancienneté",
    "Fraction 5 à 10 ans d'ancienneté",
    "Fraction plus de 10 ans d'ancienneté",
    "Indemnité de retraite",
    "IS patronal",
    "Taxe FDFP",
    "CNPS retraite",
    "CNPS AT",
    "CNPS PF",
    "Provision retraite",
    "Cotisations patronales",
    "Taux"
  ],
  "39-NOTE 27B": [
    "Effectif et masse salariale",
    "Effectifs - Nationaux",
    "Effectifs - Autres Etats de la Région (3)",
    "Effectifs - Hors Région (3)",
    "Effectifs - Total",
    "Masse salariale - Nationaux",
    "Masse salariale - Autres Etats de la Région (3)",
    "Masse salariale - Hors Région (3)",
    "Masse salariale - Total"
  ],
  "40-JOURNAL DU PERSONNEL": [
    "N°",
    "Nom et prénoms",
    "01",
    "02",
    "03",
    "04",
    "05",
    "06",
    "07",
    "08",
    "09",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20",
    "21",
    "22",
    "23",
    "24",
    "25",
    "26",
    "27",
    "28",
    "29",
    "30",
    "31"
  ],
  "41-INDICATEURS RH": [
    "Matricule",
    "Civilité",
    "Noms & Prénoms",
    "Sexe",
    "Date de Naissance",
    "Code Nationalité",
    "Situation matrimoniale",
    "Contrat",
    "Date d'Entrée",
    "Date de Sortie",
    "Code Emploi",
    "Jour(s) travaillés",
    "Brut social",
    "Congé payé",
    "Entrées du mois",
    "Sorties du mois",
    "Validation",
    "Sexe",
    "Code Nationalité",
    "Situation matrimoniale",
    "Contrat",
    "Code Emploi",
    "Âge validé",
    "< 25",
    "25-30",
    "30-40",
    "40-50",
    "> 50",
    "< 25",
    "25-30",
    "30-40",
    "40-50",
    "> 50",
    "Jour(s) travaillés",
    "Brut social",
    "Congé payé"
  ]
} as const;

export type LogipaieSheetName = keyof typeof LOGIPAIE_SHEETS;
